version: '2'
services:
    app:
        image: yamilurbina/votacion:v1
        build: .
        ports:
            - 80:3000
        command: php -S 0.0.0.0:3000 -t /app
        volumes:
            - ./:/app
    redis:
        image: redis:3.0-alpine
        command: redis-server --appendonly yes
